return {{
    "nvim-lualine/lualine.nvim",
    opts = {},
    winbar = {},
    -- config = function()
    --     require('lualine').setup {
    --         options = {
    --             icons_enabled = true,
    --             theme = 'auto',
    --             section_separators = {
    --                 left = '',
    --                 right = ''
    --             },
    --             component_separators = {
    --                 left = '',
    --                 right = ''
    --             },
    --             disabled_filetypes = {
    --                 statusline = {},
    --                 winbar = {}
    --             },
    --             ignore_focus = {},
    --             always_divide_middle = true,
    --             always_show_tabline = true,
    --             globalstatus = false,
    --             refresh = {q
    --                 statusline = 100,
    --                 tabline = 100,
    --                 winbar = 100
    --             }
    --         },
    --         sections = {
    --             lualine_a = {
    --                 'mode'
    --             },
    --             lualine_b = {
    --                 {
    --                     'branch',
    --                     icon="",
    --                     color = { fg = "#00000000", bg = "#00000000" },
    --                     padding = { left = 1, right = 1 }
    --                 },
    --                 {'diff', color = { fg = "#00000000", bg = "#00000000" }},
    --                 {'diagnostics', color = { fg = "#00000000", bg = "#00000000" }}
    --             },
    --             lualine_c = {
    --                 'filename'
    --             },
    --             lualine_x = {
    --                 'encoding', 'fileformat', 'filetype'
    --             },
    --             lualine_y = {
    --                 'progress'
    --             },
    --             lualine_z = {
    --                 'location'}
    --         },
    --         inactive_sections = {
    --             lualine_a = {},
    --             lualine_b = {},
    --             lualine_c = {'filename'},
    --             lualine_x = {'location'},
    --             lualine_y = {},
    --             lualine_z = {}
    --         },
    --         tabline = {},
    --         winbar = {},
    --         inactive_winbar = {},
    --         extensions = {}
    --     }
    -- end
}}
